# Basic Numpy Arrays

In [1]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
first = np.array([1, 3, 5, 7])
second = np.array([2,4,6,8])

In [5]:
first[0], second[0]

(1, 2)

In [6]:
first[0:2]

array([1, 3])

In [7]:
second[0], second[1], second[-1]

(2, 4, 8)

In [8]:
second[[0,1,-1]]

array([2, 4, 8])

In [9]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [10]:
print(A[:,:2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
#finished Numpy Operations lesson