# Basic Numpy Arrays

In [ ]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [13]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [18]:
first = np.array([1, 3, 5, 7])
second = np.array([2,4,6,8])

In [21]:
first[0], second[0]

(1, 2)

In [24]:
first[0:2]

array([1, 3])

In [26]:
second[0], second[1], second[-1]

(2, 4, 8)

In [29]:
second[[0,1,-1]]

array([2, 4, 8])

In [1]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

NameError: name 'np' is not defined

In [ ]:
print