## Numpy boolean arrays

In [1]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib

     |████████████████████████████████| 11.3 MB 6.8 MB/s eta 0:00:01
     |████████████████████████████████| 15.7 MB 43.3 MB/s eta 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.14.5
    Uninstalling numpy-1.14.5:
      Successfully uninstalled numpy-1.14.5
     |████████████████████████████████| 10.3 MB 9.1 MB/s eta 0:00:01    |███████▋                        | 2.4 MB 9.8 MB/s eta 0:00:01
     |████████████████████████████████| 1.1 MB 18.3 MB/s eta 0:00:01
     |████████████████████████████████| 3.0 MB 12.0 MB/s eta 0:00:01


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
a = np.array([1,2,3,4])

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
a=np.arange(4)

In [25]:
a+=100

In [35]:
hoka = np.array([0, 1, 2, 3])
aido = np.array([4, 5, 6, 7])

In [36]:
[hoka * aido]

[array([ 0,  5, 12, 21])]

In [38]:
iam = np.arange(4)
iam

array([0, 1, 2, 3])

In [42]:
iam[[0,-1]]

array([0, 3])

In [43]:
iam[[True, False, False, True]]

array([0, 3])

In [53]:
iam

array([0, 1, 2, 3])

In [54]:
iam >= 2

array([False, False,  True,  True])

In [55]:
iam[iam >= 2]

array([2, 3])